# Generated by Django 3.0.8 on 2020-07-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l', models.FloatField(default=0.0)),
                ('h', models.FloatField(default=0.0)),
                ('w', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=15)),
                ('car_brand', models.CharField(max_length=30)),
                ('ean_code', models.CharField(max_length=20)),
                ('product_name_EN', models.CharField(max_length=40)),
                ('product_name_EE', models.CharField(max_length=40)),
                ('product_info', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('warehouse_address', models.CharField(max_length=10)),
                ('location_address', models.CharField(max_length=8)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Dimension')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Weight')),
            ],
        ),
    ]
