# Generated by Django 3.0.7 on 2020-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200809_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='address',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='company_name',
            field=models.CharField(default=10, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='phone_number',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='registration_number',
            field=models.CharField(default=10, max_length=8),
            preserve_default=False,
        ),
    ]
